"""
module_id: domain.types
file: src/domain/types/__init__.py
task_id: T-303

Core domain entities for parts, constructs, hosts, libraries, assembly plans, and rules.
"""

from __future__ import annotations

from domain.types.assembly_method import (
    AssemblyMethod,
    GatewayMethod,
    GibsonLike,
    IVAMethod,
    LICMethod,
    RestrictionLigation,
    TypeIISGoldenGate,
    USERMethod,
    YeastTAR,
)
from domain.types.assembly_plan import (
    AssemblyPlanSummary,
    GatewayPlan,
    InVivoAssemblyPlan,
    LICPlan,
    OverlapAssemblyPlan,
    RestrictionLigationPlan,
    TypeIISAssemblyPlan,
    USERPlan,
    YeastTARPlan,
)
from domain.types.citation import CitationGrade, GradedCitation
from domain.types.construct import Construct
from domain.types.derivation import (
    AuthProfileId,
    CatalogueId,
    ContainerDigest,
    DatabaseId,
    DerivationEnvironment,
    DerivationEnvironmentV14,
    ExportProfile,
    GateName,
    LLMModelIdentifier,
    LLMUseSite,
    OptimisationSettings,
    PluginId,
    PredicateVersion,
    PrivacyClassification,
    PromptTemplateId,
    RandomSeedId,
    ReviewerDecision,
    RoundingPolicy,
    ScreeningScope,
    Semver,
    SopTemplateId,
    UnitsProfile,
    UserOverride,
)
from domain.types.enums import (
    AssemblyCapability,
    BiosafetyTier,
    ChassisClass,
    ContextScope,
    DownstreamUse,
    HostRole,
    ModuleLayer,
    SafetyGate,
    Severity,
    SeverityPolicy,
    SlotKind,
)
from domain.types.host import Host
from domain.types.host_compat import HostCompatibilityConstraints
from domain.types.host_context import HostContext
from domain.types.ids import (
    AssemblyMethodId,
    ConstructId,
    HostId,
    MarkerId,
    MetricId,
    ModuleId,
    OriginId,
    PartId,
    ReviewerId,
    RuleId,
    SequenceOntologyTerm,
)
from domain.types.library import (
    ExpansionPolicy,
    Library,
    construct_has_variants,
    module_has_variants,
)
from domain.types.module import Module, OneOf, Override, PartOrVariant, Variable
from domain.types.part import Part
from domain.types.signing_errors import (
    DecisionRecordPrincipalMismatchError,
    DecisionRecordTamperDetectedError,
    DecisionRecordVerificationError,
    DecisionRecordVerificationResult,
    ProfileTamperDetectedError,
    ProfileVerificationError,
    ProfileVerificationResult,
    Result,
    RevokedKeyError,
    SopTemplateTamperDetectedError,
    SopTemplateVerificationError,
    SopTemplateVerificationResult,
    UnknownKeyVersionError,
)
from domain.types.sop_template import (
    SopTemplate,
    SopTemplateRevocation,
    SopTemplateSignature,
    SopTemplateVersion,
)
from domain.types.validation_rule import ValidationRule

__all__ = [
    "AssemblyCapability",
    "AssemblyMethod",
    "AssemblyMethodId",
    "AssemblyPlanSummary",
    "AuthProfileId",
    "BiosafetyTier",
    "CatalogueId",
    "ChassisClass",
    "CitationGrade",
    "Construct",
    "ConstructId",
    "ContainerDigest",
    "ContextScope",
    "DatabaseId",
    "DecisionRecordPrincipalMismatchError",
    "DecisionRecordTamperDetectedError",
    "DecisionRecordVerificationError",
    "DecisionRecordVerificationResult",
    "DerivationEnvironment",
    "DerivationEnvironmentV14",
    "DownstreamUse",
    "ExpansionPolicy",
    "ExportProfile",
    "GateName",
    "GatewayMethod",
    "GatewayPlan",
    "GibsonLike",
    "GradedCitation",
    "Host",
    "HostCompatibilityConstraints",
    "HostContext",
    "HostId",
    "HostRole",
    "IVAMethod",
    "InVivoAssemblyPlan",
    "LICMethod",
    "LICPlan",
    "LLMModelIdentifier",
    "LLMUseSite",
    "Library",
    "MarkerId",
    "MetricId",
    "Module",
    "ModuleId",
    "ModuleLayer",
    "OneOf",
    "OptimisationSettings",
    "OriginId",
    "OverlapAssemblyPlan",
    "Override",
    "Part",
    "PartId",
    "PartOrVariant",
    "PluginId",
    "PredicateVersion",
    "PrivacyClassification",
    "ProfileTamperDetectedError",
    "ProfileVerificationError",
    "ProfileVerificationResult",
    "PromptTemplateId",
    "RandomSeedId",
    "RestrictionLigation",
    "RestrictionLigationPlan",
    "Result",
    "ReviewerDecision",
    "ReviewerId",
    "RevokedKeyError",
    "RoundingPolicy",
    "RuleId",
    "SafetyGate",
    "ScreeningScope",
    "Semver",
    "SequenceOntologyTerm",
    "Severity",
    "SeverityPolicy",
    "SlotKind",
    "SopTemplate",
    "SopTemplateId",
    "SopTemplateRevocation",
    "SopTemplateSignature",
    "SopTemplateTamperDetectedError",
    "SopTemplateVerificationError",
    "SopTemplateVerificationResult",
    "SopTemplateVersion",
    "TypeIISAssemblyPlan",
    "TypeIISGoldenGate",
    "USERMethod",
    "USERPlan",
    "UnitsProfile",
    "UnknownKeyVersionError",
    "UserOverride",
    "ValidationRule",
    "Variable",
    "YeastTAR",
    "YeastTARPlan",
    "construct_has_variants",
    "module_has_variants",
]
