"""
module_id: tools.ci_gates.audit_traceability_check
file: tools/ci_gates/audit_traceability_check.py
task_id: T-204
lifecycle_state: enforced
owning_task_id: T-204
"""

from __future__ import annotations

import ast
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, cast

import yaml  # type: ignore[import-untyped]

from tools.ci_gates._gate import GateResult, fail_gate, pass_gate, read_text, run_gate

SCAN_ROOTS = (Path("src"), Path("tools"), Path("tests"))
INDEX_PATH = Path("docs/traceability_index.md")
HEADER_KEYS = ("module_id", "file", "task_id")
TASK_RANGE_RE = re.compile(r"^(?P<prefix>T-\d+)(?P<start>[a-z])\.\.(?P<end>[a-z])$")


@dataclass(frozen=True)
class TraceabilityEntry:
    path: str
    module_id: str
    task_ids: tuple[str, ...]


def check_audit_traceability(root: Path) -> GateResult:
    messages: list[str] = []
    allowed_task_ids = _allowed_task_ids(root)
    entries = collect_traceability_entries(root, allowed_task_ids, messages)
    if messages:
        return fail_gate(*messages)

    expected = render_traceability_index(entries)
    index_path = root / INDEX_PATH
    if not index_path.is_file():
        return fail_gate(f"{INDEX_PATH.as_posix()} is missing")
    actual = read_text(index_path)
    if actual != expected:
        return fail_gate(
            f"{INDEX_PATH.as_posix()} does not match generated file-header traceability"
        )
    return pass_gate(f"{len(entries)} Python files match the traceability index")


def collect_traceability_entries(
    root: Path,
    allowed_task_ids: frozenset[str],
    messages: list[str],
) -> tuple[TraceabilityEntry, ...]:
    entries: list[TraceabilityEntry] = []
    for path in _python_files(root):
        relative_path = path.relative_to(root).as_posix()
        text = read_text(path)
        metadata = _metadata_from_docstring(text)
        if metadata is None:
            metadata = _metadata_from_constants(text)
        missing = tuple(key for key in HEADER_KEYS if not metadata.get(key))
        if missing:
            messages.append(f"{relative_path}: missing traceability header fields: {missing}")
            continue
        declared_file = str(metadata["file"])
        if declared_file != relative_path:
            messages.append(
                f"{relative_path}: file header points at {declared_file!r}, expected "
                f"{relative_path!r}"
            )
        task_ids = _normalise_task_ids(str(metadata["task_id"]))
        unresolved = tuple(task_id for task_id in task_ids if task_id not in allowed_task_ids)
        if unresolved:
            messages.append(f"{relative_path}: unresolved task_id values: {unresolved}")
        entries.append(
            TraceabilityEntry(
                path=relative_path,
                module_id=str(metadata["module_id"]),
                task_ids=task_ids,
            )
        )
    return tuple(sorted(entries, key=lambda entry: entry.path))


def render_traceability_index(entries: tuple[TraceabilityEntry, ...]) -> str:
    lines = [
        "# Traceability Index",
        "",
        "Generated by `tools.ci_gates.audit_traceability_check` from lightweight Python "
        "file headers.",
        "",
        "| File | Module ID | Task ID(s) |",
        "|---|---|---|",
    ]
    for entry in entries:
        task_ids = ", ".join(entry.task_ids)
        lines.append(f"| `{entry.path}` | `{entry.module_id}` | `{task_ids}` |")
    lines.append("")
    return "\n".join(lines)


def _python_files(root: Path) -> tuple[Path, ...]:
    files: list[Path] = []
    for scan_root in SCAN_ROOTS:
        base = root / scan_root
        if base.is_dir():
            files.extend(path for path in base.rglob("*.py") if "__pycache__" not in path.parts)
    return tuple(sorted(files, key=lambda path: path.relative_to(root).as_posix()))


def _metadata_from_docstring(text: str) -> dict[str, str] | None:
    try:
        module = ast.parse(text)
    except SyntaxError:
        return None
    docstring = ast.get_docstring(module, clean=False)
    if docstring is None:
        return None
    metadata: dict[str, str] = {}
    for line in docstring.splitlines()[:20]:
        stripped = line.strip()
        for key in HEADER_KEYS:
            marker = f"{key}:"
            if stripped.startswith(marker):
                metadata[key] = stripped.split(":", 1)[1].strip()
    return metadata if metadata else None


def _metadata_from_constants(text: str) -> dict[str, str]:
    try:
        module = ast.parse(text)
    except SyntaxError:
        return {}
    metadata: dict[str, str] = {}
    for statement in module.body:
        if isinstance(statement, ast.Assign):
            for target in statement.targets:
                if isinstance(target, ast.Name) and target.id == "MODULE_ID":
                    value = _literal_string(statement.value)
                    if value:
                        metadata["module_id"] = value
                elif isinstance(target, ast.Name) and target.id == "TRACEABILITY_FILE":
                    value = _literal_string(statement.value)
                    if value:
                        metadata["file"] = value
                elif isinstance(target, ast.Name) and target.id == "OWNING_TASKS":
                    task_ids = _literal_string_sequence(statement.value)
                    if task_ids:
                        metadata["task_id"] = ",".join(task_ids)
    return metadata


def _literal_string(value: ast.expr) -> str | None:
    if isinstance(value, ast.Constant) and isinstance(value.value, str):
        return value.value
    return None


def _literal_string_sequence(value: ast.expr) -> tuple[str, ...]:
    if not isinstance(value, ast.Tuple | ast.List):
        return ()
    items: list[str] = []
    for element in value.elts:
        literal = _literal_string(element)
        if literal is None:
            return ()
        items.append(literal)
    return tuple(items)


def _normalise_task_ids(raw: str) -> tuple[str, ...]:
    task_ids: list[str] = []
    for token in re.split(r"[,;]\s*", raw.strip()):
        if not token:
            continue
        range_match = TASK_RANGE_RE.match(token)
        if range_match:
            prefix = range_match.group("prefix")
            start = ord(range_match.group("start"))
            end = ord(range_match.group("end"))
            step = 1 if end >= start else -1
            task_ids.extend(f"{prefix}{chr(code)}" for code in range(start, end + step, step))
        else:
            task_ids.append(token)
    return tuple(task_ids)


def _allowed_task_ids(root: Path) -> frozenset[str]:
    loaded = yaml.safe_load((root / "docs" / "task_manifest.yaml").read_text(encoding="utf-8"))
    manifest = cast(dict[str, Any], loaded)
    tasks = cast(list[dict[str, Any]], manifest["tasks"])
    allowed: set[str] = {"A-018"}
    for task in tasks:
        allowed.add(str(task["task_id"]))
        expanded = task.get("expanded_task_ids", [])
        if isinstance(expanded, list):
            allowed.update(str(task_id) for task_id in expanded)
    # v0.2.1 audit-fix umbrella: read audit_fix_task_ids extension key (top-level,
    # outside tasks:) so the active_task_card_count stays at 92 (v0.2 cadence
    # scope) while letting traceability headers reference audit-fix-* IDs.
    audit_fix_ids = manifest.get("audit_fix_task_ids", [])
    if isinstance(audit_fix_ids, list):
        allowed.update(str(t) for t in audit_fix_ids)
    return frozenset(allowed)


def main() -> int:
    return run_gate("audit-traceability-check", check_audit_traceability)


if __name__ == "__main__":
    raise SystemExit(main())
