"""
module_id: tools.corpus.partition_router
file: tools/corpus/partition_router.py
task_id: T-1407
architecture_refs: § 9.3.4 partition strategy; IPQ-1 resolution (sa_free DEFAULT)
requirements_refs: FR-ML-06, FR-ML-12; BR-17; UR-14

CC-BY-SA partition routing + corpus_manifest.yaml regeneration.

Per ARCHITECTURE.md § 9.3.4 + IPQ-1: records whose `sequence_license.spdx_id` or
`annotation_license.spdx_id` matches `CC-BY-SA-*` are routed to
`docs/ml_corpus/records/cc-by-sa/`. The corpus manifest's two-partition view
(`partition: full` opt-in / `partition: sa_free` DEFAULT) is regenerated by
this tool.

Behaviour on empty corpus (v0.2 state): no records → no routing → manifest's
license_aggregate carries zero counts. Real activity begins once T-1404 +
T-1405 land records.

This is an offline curation tool, not a runtime gate. Invoked by curators
after corpus ingestion runs.
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[2]
CORPUS_ROOT = ROOT / "docs" / "ml_corpus"
RECORDS_DIR = CORPUS_ROOT / "records"
CC_BY_SA_DIR = RECORDS_DIR / "cc-by-sa"
MANIFEST_FILE = CORPUS_ROOT / "corpus_manifest.yaml"


def _is_cc_by_sa(spdx: str | None) -> bool:
    return isinstance(spdx, str) and spdx.upper().startswith("CC-BY-SA")


def _load_records() -> list[tuple[Path, dict[str, Any]]]:
    import json

    records: list[tuple[Path, dict[str, Any]]] = []
    if not RECORDS_DIR.exists():
        return records
    for path in sorted(RECORDS_DIR.rglob("*.json")):
        if not path.is_file():
            continue
        try:
            records.append((path, json.loads(path.read_text(encoding="utf-8"))))
        except Exception:
            continue
    return records


def route_records(dry_run: bool = False) -> tuple[int, int]:
    """Move CC-BY-SA records into cc-by-sa/. Returns (moved_count, skipped_count)."""
    moved = 0
    skipped = 0
    CC_BY_SA_DIR.mkdir(parents=True, exist_ok=True)
    for path, record in _load_records():
        if "cc-by-sa" in path.parts:
            continue  # already routed
        license_obj = record.get("license") or {}
        seq_lic = license_obj.get("sequence_license") or {}
        ann_lic = license_obj.get("annotation_license") or {}
        if _is_cc_by_sa(seq_lic.get("spdx_id")) or _is_cc_by_sa(ann_lic.get("spdx_id")):
            target = CC_BY_SA_DIR / path.name
            if dry_run:
                print(f"[dry-run] would route {path.relative_to(ROOT)} -> {target.relative_to(ROOT)}")
            else:
                target.write_text(path.read_text(encoding="utf-8"), encoding="utf-8")
                path.unlink()
            moved += 1
        else:
            skipped += 1
    return moved, skipped


def regenerate_manifest(dry_run: bool = False) -> dict[str, Any]:
    """Recompute corpus_manifest.yaml's license_aggregate + partition counts."""
    records = _load_records()
    by_seq_lic: Counter[str] = Counter()
    by_ann_lic: Counter[str] = Counter()
    checked = 0
    cc_by_sa_count = 0
    attribution_count = 0
    by_source: Counter[str] = Counter()

    for path, record in records:
        license_obj = record.get("license") or {}
        seq_lic = license_obj.get("sequence_license") or {}
        ann_lic = license_obj.get("annotation_license") or {}
        seq_spdx = str(seq_lic.get("spdx_id", "unknown"))
        ann_spdx = str(ann_lic.get("spdx_id", "unknown"))
        by_seq_lic[seq_spdx] += 1
        by_ann_lic[ann_spdx] += 1
        if _is_cc_by_sa(seq_spdx) or _is_cc_by_sa(ann_spdx):
            cc_by_sa_count += 1
        if seq_lic.get("attribution_required") or ann_lic.get("attribution_required"):
            attribution_count += 1
        if (record.get("snapgene_crosscheck") or {}).get("checked") is True:
            checked += 1
        provenance = record.get("provenance") or {}
        by_source[str(provenance.get("source", "unknown"))] += 1

    total = len(records)
    sa_free_count = total - cc_by_sa_count

    aggregate: dict[str, Any] = {
        "total_records": total,
        "by_sequence_license": dict(sorted(by_seq_lic.items())),
        "by_annotation_license": dict(sorted(by_ann_lic.items())),
        "by_provenance_source": dict(sorted(by_source.items())),
        "partition_sa_free": {
            "record_count": sa_free_count,
            "fraction": (sa_free_count / total) if total else 0.0,
        },
        "attribution_obligations": {
            "records_requiring_attribution": attribution_count,
            "attribution_text_file": "LICENSES/THIRD_PARTY_NOTICES.md",
        },
        "cross_check_coverage": {
            "checked": checked,
            "unchecked": total - checked,
            "fraction_checked": (checked / total) if total else 0.0,
        },
    }

    if not MANIFEST_FILE.exists():
        if not dry_run:
            print(
                f"[partition_router] {MANIFEST_FILE.relative_to(ROOT)} does not exist; "
                "skipping manifest regeneration (will be present once T-1401 scaffold lands "
                "— it already does at v0.2, so this branch is informational).",
                file=sys.stderr,
            )
        return aggregate

    manifest = yaml.safe_load(MANIFEST_FILE.read_text(encoding="utf-8")) or {}
    manifest["license_aggregate"] = aggregate
    manifest["partitions"] = {
        "full": {
            "description": manifest.get("partitions", {}).get("full", {}).get(
                "description",
                "All records including cc-by-sa/. Opt-in for research-only training runs.",
            ),
            "record_count": total,
        },
        "sa_free": {
            "description": manifest.get("partitions", {}).get("sa_free", {}).get(
                "description",
                "Default partition. Excludes records routed to cc-by-sa/.",
            ),
            "record_count": sa_free_count,
        },
    }
    if dry_run:
        print(f"[dry-run] would update {MANIFEST_FILE.relative_to(ROOT)} with new aggregate")
    else:
        MANIFEST_FILE.write_text(
            yaml.safe_dump(manifest, sort_keys=False, allow_unicode=True),
            encoding="utf-8",
        )
    return aggregate


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Route CC-BY-SA records into cc-by-sa/ and regenerate corpus manifest.",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print actions, do not write.")
    parser.add_argument("--skip-routing", action="store_true", help="Only regenerate manifest.")
    parser.add_argument("--skip-manifest", action="store_true", help="Only route records.")
    args = parser.parse_args(argv)

    if not args.skip_routing:
        moved, skipped = route_records(dry_run=args.dry_run)
        print(f"partition_router: routed {moved} CC-BY-SA record(s); {skipped} other(s) untouched")
    if not args.skip_manifest:
        aggregate = regenerate_manifest(dry_run=args.dry_run)
        print(
            f"partition_router: manifest aggregate — {aggregate['total_records']} records, "
            f"sa_free fraction = {aggregate['partition_sa_free']['fraction']:.2%}, "
            f"cross-check coverage = {aggregate['cross_check_coverage']['fraction_checked']:.2%}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
