"""
module_id: tools.initial_task_brief_generator
file: tools/initial_task_brief_generator.py
task_id: T-204

Generate seed task briefs from docs/task_manifest.yaml.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml  # type: ignore[import-untyped]

ROOT = Path(__file__).resolve().parents[1]


def brief_text(task: dict[str, object]) -> str:
    task_id = str(task["task_id"])
    title = str(task["title"])
    return f"""# {task_id} Task Brief — {title}

## Scope

Seed brief generated from `docs/task_manifest.yaml`.
`/dev-orchestrator` refines this before assignment.

## Acceptance

```yaml
task_id: {task_id}
required_checks: []
```

## Notes

Generated by `tools/initial_task_brief_generator.py`.
"""


def generate(root: Path, *, overwrite: bool = False) -> list[Path]:
    manifest = yaml.safe_load((root / "docs" / "task_manifest.yaml").read_text(encoding="utf-8"))
    output_dir = root / "tasks" / "task_brief"
    output_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for task in manifest["tasks"]:
        path = output_dir / f"{task['task_id']}.md"
        if path.exists() and not overwrite:
            continue
        path.write_text(brief_text(task), encoding="utf-8", newline="\n")
        written.append(path)
    return written


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--overwrite", action="store_true", help="Rewrite existing briefs.")
    args = parser.parse_args()
    for path in generate(ROOT, overwrite=args.overwrite):
        print(path.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
